### PR TITLE
corrected spelling of the word "latest"

### PR DESCRIPTION
**Pull request by ashita5444**
Earlier simple 'latest' word was written as "lasest', which has no meaning.

### CODE REVIEW

**Comment by mm2745** [comment]
Spam

**Comment by ashita5444** [comment]
Is lasest a correct word ?

**Comment by mm2745** [comment]
@ashita5444 this project is closed and not planned to development it , the project has moved to https://mspcontrol.org/. Find another repository to be counted toward Hacktoberfest

**Comment by ashita5444** [comment]
Okay, thank you.

**Pull request closed without merging**
